language: ruby
rvm:
  - 1.9.3
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
before_script:
  - psql -c 'CREATE USER pg_admin WITH PASSWORD 'pg_admin';' -U postgres
  - psql -c 'ALTER ROLE pg_admin SUPERUSER;' -U postgres
  - psql -c 'create database amazon_test;' -U postgres